name: Create zip file

on:
  push:
    tags:
      - '*'

jobs:
  zip:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install zip
      - run: zip -r DonoguysPlus.zip icons/ *.js manifest.json 
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: DonoguysPlus.zip
